# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gfetch < Formula
  desc "A fast, terminal-based git repository info tool"
  homepage "https://github.com/fayssal-elmofatiche/gfetch"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fayssal-elmofatiche/gfetch/releases/download/v0.7.2/gfetch_0.7.2_darwin_amd64.tar.gz"
      sha256 "12ca26d0305d3dabb514cf260b9fcdb3adc6d016d5babc7b83480f8b814f8bd4"

      define_method(:install) do
        bin.install "gfetch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fayssal-elmofatiche/gfetch/releases/download/v0.7.2/gfetch_0.7.2_darwin_arm64.tar.gz"
      sha256 "0d654a47c0083a6b025727615b0860df274aa24704afcfb0ad0518fc5395a40f"

      define_method(:install) do
        bin.install "gfetch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fayssal-elmofatiche/gfetch/releases/download/v0.7.2/gfetch_0.7.2_linux_amd64.tar.gz"
      sha256 "4e0322073eb3f355520098929259574c365efd5cdd56acf8a40adee65034c1c9"
      define_method(:install) do
        bin.install "gfetch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fayssal-elmofatiche/gfetch/releases/download/v0.7.2/gfetch_0.7.2_linux_arm64.tar.gz"
      sha256 "75c58b165b9d1a488247158428714bccdf66012a760501d7b00cb75dcb832019"
      define_method(:install) do
        bin.install "gfetch"
      end
    end
  end
end
