# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtop < Formula
  desc "A fast, terminal-based git repository info tool"
  homepage "https://github.com/fayssal-elmofatiche/gtop"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fayssal-elmofatiche/gtop/releases/download/v0.4.0/gtop_0.4.0_darwin_amd64.tar.gz"
      sha256 "bbd2d244716b4018e1619b84f1f08bd5adcd06e16e03661de83f7c2981d17c01"

      def install
        bin.install "gtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fayssal-elmofatiche/gtop/releases/download/v0.4.0/gtop_0.4.0_darwin_arm64.tar.gz"
      sha256 "3586c9023c5a84a06a450f9ed1917e1c338af1a5ed6fe74db464dc2b65709751"

      def install
        bin.install "gtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fayssal-elmofatiche/gtop/releases/download/v0.4.0/gtop_0.4.0_linux_amd64.tar.gz"
      sha256 "49fdd3e9be5368e6bd928bb1fbfc22db277da72f222755868f654f4b6f118428"
      def install
        bin.install "gtop"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fayssal-elmofatiche/gtop/releases/download/v0.4.0/gtop_0.4.0_linux_arm64.tar.gz"
      sha256 "e461555c9de0ddd01ccd306090bee59bf3e052ae7ce60a02fea7f2f879e198a6"
      def install
        bin.install "gtop"
      end
    end
  end
end
