# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtop < Formula
  desc "A fast, terminal-based git repository info tool"
  homepage "https://github.com/fayssal-elmofatiche/gtop"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fayssal-elmofatiche/gtop/releases/download/v0.5.0/gtop_0.5.0_darwin_amd64.tar.gz"
      sha256 "5da8f9a0bfb85ac8e4d35d9c75b1062fd18cc3d932bf630a1321e867889a487c"

      def install
        bin.install "gtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fayssal-elmofatiche/gtop/releases/download/v0.5.0/gtop_0.5.0_darwin_arm64.tar.gz"
      sha256 "78d16c1f0162ec489cd751bf2a49a01e80e681228f78670fe27a02159767d61a"

      def install
        bin.install "gtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fayssal-elmofatiche/gtop/releases/download/v0.5.0/gtop_0.5.0_linux_amd64.tar.gz"
      sha256 "9e6c2e2d2033aaf8dee404db4a7024b037c1fb6d06c42dce5c0c094b63c71c99"
      def install
        bin.install "gtop"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fayssal-elmofatiche/gtop/releases/download/v0.5.0/gtop_0.5.0_linux_arm64.tar.gz"
      sha256 "29e71e81aabce25244938f8f3d0ddfb27a9ea8e4075fbb03768c3a5641ca4833"
      def install
        bin.install "gtop"
      end
    end
  end
end
